POST http://localhost:3000/api/creacliente HTTP/1.1
content-type: application/json

{
    "nombre": "George",
    "apellido": "Kusunoki Miller",
    "fechaNacimiento": "{{$localDatetime '1992-09-18'}}"
}
